"""
SP18 - Multi-Rate Audio Resampling Engine
Final reusable engine.

Core design:
    input WAV -> rational-rate reduction -> anti-alias FIR -> polyphase resampling -> output WAV

No plots are generated by this engine. It returns audio plus numerical metadata.
"""


from __future__ import annotations

from dataclasses import dataclass, asdict
from math import gcd
from pathlib import Path
from typing import Optional, Union

import numpy as np
import soundfile as sf
from scipy import signal


Number = Union[int, float]


@dataclass
class FilterInfo:
    taps: int
    passband_hz: float
    stopband_hz: float
    transition_hz: float
    attenuation_target_db: float
    measured_stopband_db: float
    passband_ripple_db: float
    group_delay_input_samples: float
    group_delay_ms: float


@dataclass
class ResamplingReport:
    input_file: Optional[str]
    output_file: Optional[str]
    input_sample_rate: int
    output_sample_rate: int
    input_samples: int
    output_samples: int
    channels: int
    duration_seconds: float
    L: int
    M: int
    filter: dict
    processing_time_seconds: Optional[float]
    input_rms: float
    output_rms: float
    input_peak: float
    output_peak: float
    output_clipped: bool
    input_out_of_band_rms: float
    input_out_of_band_fraction_percent: float
    rmse_vs_reference: Optional[float] = None
    snr_vs_reference_db: Optional[float] = None

    def to_dict(self):
        return asdict(self)


class SP18Resampler:
    """
    Final SP18 rational audio resampling engine.

    The actual conversion uses scipy's optimized polyphase implementation
    (resample_poly) with our explicitly designed Kaiser FIR.
    """

    def __init__(
        self,
        attenuation_db: float = 70.0,
        passband_fraction: float = 0.85,
    ):
        if attenuation_db <= 0:
            raise ValueError("attenuation_db must be positive.")
        if not 0 < passband_fraction < 1:
            raise ValueError("passband_fraction must be between 0 and 1.")
        self.attenuation_db = float(attenuation_db)
        self.passband_fraction = float(passband_fraction)

    @staticmethod
    def ratio(fs_in: int, fs_out: int) -> tuple[int, int]:
        g = gcd(int(fs_in), int(fs_out))
        return fs_out // g, fs_in // g

    def design_filter(self, fs_in: int, fs_out: int):
        L, M = self.ratio(fs_in, fs_out)

        # The FIR operates at the conceptual interpolation rate.
        fs_internal = fs_in * L

        # The filter must reject content beyond min(fs_in, fs_out)/2:
        # when upsampling, spectral images of the input start appearing at
        # fs_in/2 (not fs_out/2), and when downsampling the output can't
        # represent anything past fs_out/2. Using fs_out alone here left
        # upsampling images completely unattenuated.
        target_nyquist = min(fs_in, fs_out) / 2.0

        passband = self.passband_fraction * target_nyquist
        stopband = target_nyquist
        transition = stopband - passband
        cutoff = (passband + stopband) / 2.0

        N = int(np.ceil(
            (self.attenuation_db - 8.0)
            / (2.285 * 2.0 * np.pi * transition / fs_internal)
        ))
        if N % 2 == 0:
            N += 1

        n = np.arange(N, dtype=np.float64) - (N - 1) / 2.0
        h = (
            2.0 * cutoff / fs_internal
            * np.sinc(2.0 * cutoff * n / fs_internal)
        )

        if self.attenuation_db > 50:
            beta = 0.1102 * (self.attenuation_db - 8.7)
        elif self.attenuation_db >= 21:
            beta = (
                0.5842 * (self.attenuation_db - 21.0) ** 0.4
                + 0.07886 * (self.attenuation_db - 21.0)
            )
        else:
            beta = 0.0

        h *= np.kaiser(N, beta)

        # scipy.signal.resample_poly applies an "up" gain internally
        # (it does h *= up on whatever filter we pass it), so our filter
        # should be normalized to unity DC gain here; scipy supplies the
        # required L-factor gain for interpolation on its own.
        h /= np.sum(h)

        # Measure filter characteristics at the original-rate frequency axis.
        # h already has unity DC gain at this point (see normalization
        # above), so analyzing h directly gives correct passband/stopband
        # dB figures relative to 0 dB. Do NOT multiply by L here: that L
        # only belongs inside scipy.signal.resample_poly's own internal
        # scaling, not in this analysis.
        w, H = signal.freqz(h, worN=65536, fs=fs_internal)
        Hmag = np.abs(H)
        HdB = 20.0 * np.log10(
            np.maximum(Hmag / max(Hmag[0], 1e-14), 1e-14)
        )

        pm = w <= passband
        sm = w >= stopband
        ripple = float(np.max(HdB[pm]) - np.min(HdB[pm]))
        stop_max = float(np.max(HdB[sm]))

        # The filter has linear phase. Its delay is expressed in samples
        # of the input-rate signal for the common L=1 decimation case.
        group_delay_internal = (N - 1) / 2.0
        group_delay_input = group_delay_internal / L
        group_delay_ms = group_delay_input / fs_in * 1000.0

        info = FilterInfo(
            taps=N,
            passband_hz=passband,
            stopband_hz=stopband,
            transition_hz=transition,
            attenuation_target_db=self.attenuation_db,
            measured_stopband_db=stop_max,
            passband_ripple_db=ripple,
            group_delay_input_samples=group_delay_input,
            group_delay_ms=group_delay_ms,
        )
        return h, info, L, M

    @staticmethod
    def _ensure_channels(audio: np.ndarray):
        audio = np.asarray(audio, dtype=np.float64)
        if audio.ndim == 1:
            return audio[:, None], 1
        if audio.ndim == 2:
            return audio, audio.shape[1]
        raise ValueError("Audio must be mono or 2-D channel data.")

    @staticmethod
    def _rms(x):
        return float(np.sqrt(np.mean(np.square(x)))) if np.asarray(x).size else 0.0

    @staticmethod
    def _peak(x):
        return float(np.max(np.abs(x))) if x.size else 0.0

    @staticmethod
    def _out_of_band_rms(audio, fs, stopband_hz):
        """
        Estimate RMS energy above the new Nyquist/stopband.
        Uses a Hann-windowed FFT and integrates power above stopband.
        """
        a = np.asarray(audio, dtype=np.float64)
        if a.ndim == 2:
            a = np.mean(a, axis=1)

        n = len(a)
        if n < 16:
            return 0.0, 0.0

        w = np.hanning(n)
        X = np.fft.rfft(a * w)
        f = np.fft.rfftfreq(n, 1.0 / fs)

        total = np.sum(np.abs(X) ** 2)
        mask = f >= stopband_hz
        high = np.sum(np.abs(X[mask]) ** 2)

        frac = float(high / total) if total > 0 else 0.0
        return float(np.sqrt(max(high, 0.0) / max(total, 1.0)) * np.sqrt(np.mean(a*a))), frac

    def resample_array(self, audio, fs_in: int, fs_out: int):
        """
        Resample mono or multi-channel floating-point audio.

        Returns:
            output_audio, filter_info, L, M
        """
        if fs_in <= 0 or fs_out <= 0:
            raise ValueError("Sample rates must be positive integers.")

        a, channels = self._ensure_channels(audio)

        if fs_in == fs_out:
            return a[:, 0] if channels == 1 else a.copy(), None, 1, 1

        h, info, L, M = self.design_filter(int(fs_in), int(fs_out))

        outputs = []
        for c in range(channels):
            y = signal.resample_poly(
                a[:, c],
                up=L,
                down=M,
                window=h,
                padtype="constant",
            )
            outputs.append(y)

        y = np.stack(outputs, axis=1)
        expected = int(np.ceil(a.shape[0] * fs_out / fs_in))
        y = y[:expected]

        if channels == 1:
            y = y[:, 0]

        return y, info, L, M

    def resample_file(
        self,
        input_file: Union[str, Path],
        output_file: Union[str, Path],
        fs_out: int,
        reference_audio: Optional[np.ndarray] = None,
    ) -> ResamplingReport:
        import time

        input_file = str(input_file)
        output_file = str(output_file)

        audio, fs_in = sf.read(input_file, always_2d=False)
        audio = np.asarray(audio, dtype=np.float64)

        if audio.ndim == 1:
            channels = 1
        elif audio.ndim == 2:
            channels = audio.shape[1]
        else:
            raise ValueError("Input WAV must be mono or multi-channel.")

        input_samples = audio.shape[0]
        input_rms = self._rms(audio)
        input_peak = self._peak(audio)

        t0 = time.perf_counter()
        output, info, L, M = self.resample_array(audio, int(fs_in), int(fs_out))
        elapsed = time.perf_counter() - t0

        output_rms = self._rms(output)
        output_peak = self._peak(output)
        output_clipped = bool(output_peak > 1.0 + 1e-12)

        # WAV output is PCM-16, with safe scaling only if necessary.
        write_audio = np.asarray(output, dtype=np.float64)
        if output_clipped:
            write_audio = write_audio / output_peak

        sf.write(output_file, write_audio, int(fs_out), subtype="PCM_16")

        if info is None:
            # Same-rate conversion.
            stopband = fs_out / 2.0
            out_band_rms, out_band_frac = self._out_of_band_rms(
                audio, int(fs_in), stopband
            )
            filter_dict = {}
            L, M = 1, 1
        else:
            stopband = info.stopband_hz
            out_band_rms, out_band_frac = self._out_of_band_rms(
                audio, int(fs_in), stopband
            )
            filter_dict = asdict(info)

        rmse = None
        snr = None
        if reference_audio is not None:
            ref = np.asarray(reference_audio, dtype=np.float64)
            if ref.shape != np.asarray(output).shape:
                raise ValueError("reference_audio shape must match output.")
            err = np.asarray(output) - ref
            rmse = self._rms(err)
            ep = float(np.mean(err * err))
            sp = float(np.mean(ref * ref))
            if ep > 0:
                snr = float(10.0 * np.log10(sp / ep))

        report = ResamplingReport(
            input_file=input_file,
            output_file=output_file,
            input_sample_rate=int(fs_in),
            output_sample_rate=int(fs_out),
            input_samples=int(input_samples),
            output_samples=int(np.asarray(output).shape[0]),
            channels=int(channels),
            duration_seconds=float(np.asarray(output).shape[0] / fs_out),
            L=int(L),
            M=int(M),
            filter=filter_dict,
            processing_time_seconds=float(elapsed),
            input_rms=input_rms,
            output_rms=output_rms,
            input_peak=input_peak,
            output_peak=output_peak,
            output_clipped=output_clipped,
            input_out_of_band_rms=out_band_rms,
            input_out_of_band_fraction_percent=100.0 * out_band_frac,
            rmse_vs_reference=rmse,
            snr_vs_reference_db=snr,
        )
        return report


def resample_wav(
    input_file,
    output_file,
    fs_out,
    attenuation_db=70.0,
    passband_fraction=0.85,
):
    """Convenience API for one-shot WAV resampling."""
    engine = SP18Resampler(
        attenuation_db=attenuation_db,
        passband_fraction=passband_fraction,
    )
    return engine.resample_file(input_file, output_file, fs_out)
